name: Register a new model
description: Register a new model (source_id) for the CORDEX-CMIP6 CV.
title: "source_id registration of ..."
labels: ["Register source-id"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time!
        Please, read carefully each of the placeholder instructions.

  - type: input
    id: label
    attributes:
      label: label
      description: >
        A short acronym that uniquely identifies your model and distinguishes
        it from other versions used in CORDEX-CMIP6.
        Dots and spaces are allowed to improve legibility and reflect actual
        model names.
      placeholder: ex. `REMO2020` or `WRF v4.4.2-Q`
    validations:
      required: true

  - type: input
    id: label_extended
    attributes:
      label: label_extended
      description: >
        A longer description of the model name, possibly including the acronym expanded.
      placeholder: ex. `Weather Research and Forecasting model version 4.4.2, CORDEX WRF Community configuration Q`
    validations:
      required: true

  - type: input
    id: source_id
    attributes:
      label: source_id
      description: >
        An identifier corresponding to `label` but with forbidden
        characters either removed or replaced by a hyphen (`-`).
        The `source_id` will appear in the ESGF search interface and in filenames
        a subdirectory names.
        Restrict characters used in source_id to letters, numbers and hyphens
        (e.g. NO dots, spaces or underscores are allowed).
        There is a limitation of 25 characters for this field.
      placeholder: ex. `REMO2020` or `WRF442Q`
    validations:
      required: true

  - type: dropdown
    id: source_type
    attributes:
      label: source_type
      description: >
        The type of model. Choose from the dropdown menu. If you feel that a new
        source type should be added, please, open first an issue requesting to update
        https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/main/CORDEX-CMIP6_source_type.json
      multiple: False
      options:
        - ARCM
        - AORCM
        - AGCM
    validations:
      required: true

  - type: input
    id: release_year
    attributes:
      label: release_year
      description: >
        Release year of the model. Provide when relevant.
        This should be the year your model was first used in a scientific study.
        This year should reflect the "generation" of models rather than
        distinguishing between closely-related versions.
      placeholder: ex. `1999` or `2015`
    validations:
      required: false

  - type: dropdown
    id: activity_participation
    attributes:
      label: activity_participation
      description: >
        The CORDEX-CMIP6 activities that you intend to run experiment simulations.
        DD is for dynamical downscaling and ESD for empirical-statistical downscaling.
      multiple: true
      options:
        - DD
        - ESD
    validations:
      required: true

  - type: input
    id: institution_id
    attributes:
      label: institution_id
      description: >
        Comma-separated list of all institutions (by institution_id) who are
        responsible for one or more CORDEX-CMIP6 simulations with this
        specific `source_id`. Additional institutions can be added to the list
        as needed, but only institutions registered may be included.
        See https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/main/CORDEX-CMIP6_institution_id.json
      placeholder: ex. `GERICS` or `NORCE-UCAN` or `HCLIMcom-METNo,HCLIMcom-SMHI`
    validations:
      required: true

  - type: input
    id: futher_info_url
    attributes:
      label: futher_info_url
      description: >
        A URL that points to the latest documentation of this model version.
        You can initially register with a general documentation URL for the model,
        but it should be updated as detailed information of the exact model
        version registered is published.
      placeholder: ex. `https://github.com/CORDEX-WRF-community/euro-cordex-cmip6`
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: What license do you choose?
      multiple: false
      options:
        - CC0
        - CC BY 4.0
    validations:
      required: true
